//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurityAnalyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurityAnalyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Linq.Enumerable, Where: TSource
        ///System.Linq.Enumerable, Select: TSource, TResult
        ///System.Linq.Enumerable, SelectMany: TSource,TCollection,TResult
        ///System.Linq.Enumerable, First: TSource
        ///System.Linq.Enumerable, GroupBy: TSource,TElement,TResult
        ///System.Collections.Generic.List`1, ConvertAll(System.Converter`2): TOutput
        ///System.Linq.ImmutableArrayExtensions, Select: T, TResult.
        /// </summary>
        internal static string NotUsedAsObjectsTypeParameters {
            get {
                return ResourceManager.GetString("NotUsedAsObjectsTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Xml.XmlDocument, CreateElement
        ///System.Xml.XmlElement, SetAttribute
        ///System.Array, System.Collections.IList.set_Item(System.Int32, System.Object)
        ///System.Collections.Generic.List`1, set_Item(System.Int32, T)
        ///System.Collections.Generic.List`1, set_Capacity
        ///System.Collections.Generic.List`1, Add(T)
        ///System.Collections.Generic.List`1, AddRange(System.Collections.Generic.IEnumerable`1)
        ///System.Collections.Generic.List`1, Clear()
        ///System.Collections.Generic.List`1, Insert(System.Int32, T)
        ///System.Collec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PureExceptLocallyMethods {
            get {
                return ResourceManager.GetString("PureExceptLocallyMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Xml.XmlNode, get_OuterXml
        ///System.Array, System.Collections.IList.get_Item
        ///System.Array, GetEnumerator
        ///System.Collections.Generic.List`1, GetEnumerator
        ///System.Collections.Generic.List`1, System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator
        ///System.Collections.Generic.List`1, System.Collections.IEnumerable.GetEnumerator
        ///System.Collections.Generic.List`1, get_Capacity
        ///System.Collections.Generic.List`1, get_Count
        ///System.Collections.Generic.List`1, get_Item
        ///System.Collections.Generic.List`1, Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PureExceptReadLocallyMethods {
            get {
                return ResourceManager.GetString("PureExceptReadLocallyMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String, ToString
        ///System.String, Equals(System.String)
        ///System.String, Equals(System.String, System.String)
        ///System.String, Equals(System.Object)
        ///System.String, Join(System.String, System.String[])
        ///System.String, Join(System.String, System.Object[])
        ///System.String, Join(System.String, System.Collections.Generic.IEnumerable`1)
        ///System.String, Join(System.String, System.String[], System.Int32, System.Int32)
        ///System.String, ToCharArray()
        ///System.String, ToCharArray(System.Int32, System.Int32)
        ///System. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PureMethods {
            get {
                return ResourceManager.GetString("PureMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Int32, ToString(System.String, System.IFormatProvider).
        /// </summary>
        internal static string PureOnInvariantIFormatProviderMethods {
            get {
                return ResourceManager.GetString("PureOnInvariantIFormatProviderMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Linq.Enumerable
        ///System.Linq.IGrouping`2
        ///System.Nullable`1
        ///System.Collections.Immutable.ImmutableArray`1
        ///System.Collections.Immutable.ImmutableArray.
        /// </summary>
        internal static string PureTypes {
            get {
                return ResourceManager.GetString("PureTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Xml.XmlDocument, CreateElement
        ///System.Collections.Immutable.ImmutableArray`1, SetItem(System.Int32, T).
        /// </summary>
        internal static string ReturnsNewObjectMethods {
            get {
                return ResourceManager.GetString("ReturnsNewObjectMethods", resourceCulture);
            }
        }
    }
}
